# Comparision of Machine Learning Methods vs Rule Based
* Traditionally, Educational Institutions use rule based models to generate risk score which then informs resource allocation. For example, *[Hiller et al, 1999](https://www.ets.org/Media/Research/pdf/RD_Connections18.pdf)*

* Instead, we'll build a simple model using basic ML techniques and demonstrate why the risk scores generated are better

## Setup

* First, we need to generate simulated data and read it into a data frame

In [1]:
%run sim.py

In [2]:
student_df = pd.read_csv('./students.csv', d)

In [3]:
student_df

,Unnamed: 0,name,sid,race,college,psat,gpa,honors,var0,var1,var2,var3,var4,var5,var6,var7,var8,var9
0,0,Jonathan Brock,1,cardassian,Mount Yo-yo College,91,1.153619,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Edward Lin,2,romulan,Mount Yo-yo College,97,2.112211,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Nihar Bashyakarla,3,vulcan,Aardvark University,127,2.776472,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Jonathan Shah,4,romulan,Cappybara Community College,110,1.519417,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Nihar Eneva,5,cardassian,Aardvark University,96,2.297732,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,Kayla Brown,6,cardassian,Institute of Banana Harvesting,239,3.658241,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,Varoon Velez,7,cardassian,Cranberry Lemon University,156,3.223100,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,Andrea Gee,8,romulan,Cappybara Community College,96,1.619121,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,Tom McFowland,9,romulan,Aardvark University,111,2.051667,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,Andrea Meinshausen,10,klingon,Mount Yo-yo College,81,1.234470,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,Michelangelo Eneva,11,cardassian,Aardvark University,219,3.130481,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,Nihar Leiby,12,klingon,Cranberry Lemon University,202,3.317433,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,Andrea Ashktorab,13,cardassian,Aardvark University,60,1.150888,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,Tom Leiby,14,romulan,Whale University,182,3.200492,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,Varoon McFowland,15,vulcan,Aardvark University,136,1.730229,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,Nick Jacobs,16,vulcan,Starfish University,170,3.644154,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,John Ashktorab,17,klingon,Cranberry Lemon University,239,3.870839,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,Vidhur Shah,18,vulcan,Mount Yo-yo College,65,1.491911,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,Kayla Brown,19,vulcan,Cappybara Community College,100,2.136030,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,Allen Lin,20,klingon,Whale University,176,3.110362,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,Paul Brock,21,cardassian,Aardvark University,91,1.676617,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21,John Brown,22,klingon,Aardvark University,153,2.099467,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,Varoon Shah,23,romulan,Aardvark University,119,1.720397,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,Edward Auerbach,24,klingon,Aardvark University,125,2.175895,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24,Edward Brock,25,romulan,Starfish University,203,3.329924,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,Nick Su,26,klingon,Starfish University,176,3.728348,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,Chris Plagge,27,vulcan,Cappybara Community College,119,1.780217,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,Rayid Brown,28,vulcan,Mount Yo-yo College,60,1.127364,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,Zahra D'Agnostino,29,romulan,Cappybara Community College,124,2.577635,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,Sam Plagge,30,klingon,Aardvark University,156,2.178942,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3970,3970,Edward Lin,3971,vulcan,Aardvark University,128,2.452394,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3971,3971,Andrea McFowland,3972,klingon,Cranberry Lemon University,182,3.042055,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3972,3972,Elena Bashyakarla,3973,cardassian,Starfish University,134,2.447271,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3973,3973,Edward Shah,3974,vulcan,Mount Yo-yo College,80,1.260613,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3974,3974,Sam Ghani,3975,cardassian,Cappybara Community College,90,1.873919,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3975,3975,John Eneva,3976,romulan,Cappybara Community College,114,1.805715,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3976,3976,Juan-Pablo Meinshausen,3977,cardassian,Starfish University,230,3.447793,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3977,3977,Sam Rowe,3978,cardassian,Starfish University,207,2.948400,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3978,3978,Andrea Gee,3979,klingon,Cranberry Lemon University,229,3.953616,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3979,3979,Nihar Mader,3980,klingon,Aardvark University,182,2.445633,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3980,3980,Juan-Pablo Rowe,3981,klingon,Cranberry Lemon University,188,2.927206,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3981,3981,Juan-Pablo Adhikari,3982,klingon,Mount Yo-yo College,60,1.226394,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3982,3982,Zahra Brock,3983,klingon,Starfish University,182,3.590283,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3983,3983,Sophia Lin,3984,vulcan,Whale University,136,2.721514,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3984,3984,Nihar Rowe,3985,klingon,Cappybara Community College,85,1.401389,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3985,3985,Michelangelo Brock,3986,vulcan,Institute of Banana Harvesting,60,1.220206,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3986,3986,Rayid Brock,3987,cardassian,Starfish University,233,3.648175,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3987,3987,Chris Eneva,3988,klingon,Whale University,177,3.609543,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3988,3988,Zahra D'Agnostino,3989,klingon,Mount Yo-yo College,110,2.490992,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3989,3989,Varoon Adhikari,3990,vulcan,Aardvark University,61,1.527110,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3990,3990,Nihar Brock,3991,vulcan,Cappybara Community College,60,1.116716,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3991,3991,Elena Ashktorab,3992,romulan,Aardvark University,161,2.889935,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3992,3992,Sophia Velez,3993,cardassian,Aardvark University,124,2.670890,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3993,3993,Sophia Su,3994,cardassian,Cranberry Lemon University,240,3.579996,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3994,3994,Andrea McFowland,3995,romulan,Starfish University,201,2.600978,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3995,3995,Zahra Velez,3996,cardassian,Cranberry Lemon University,187,2.882309,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3996,3996,Paul Plagge,3997,vulcan,Whale University,150,2.107084,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3997,3997,Varoon Meinshausen,3998,vulcan,Cappybara Community College,115,1.979918,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3998,3998,Tom Alice,3999,romulan,Institute of Banana Harvesting,74,1.703778,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3999,3999,Nathan Eneva,4000,vulcan,Aardvark University,150,2.939533,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN